version: "3"
services:
  feed:
    build: 
      context: .
      args: 
        NODE_ENV: dev
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=dev
    command: nodemon src/server/index.js